version: "2"

services:
  swagger-aor-generator:
    build: .
    image: sniperkit/swagger-aor-generator:py3.6-alpine
    command: ["make", "demo-all"]
    volumes:
      - ./shared:/app/shared
    environment:
      PYTHONPATH_RUNTIME: /app/
      PYTHONPATH_BUILD: /install/
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONIOENCODING: UTF-8
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      LOG_LEVEL: DEBUG